//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountManagement.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserInfo", ReplyAction="http://tempuri.org/IService1/GetUserInfoResponse")]
        System.Data.DataSet GetUserInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserInfo", ReplyAction="http://tempuri.org/IService1/GetUserInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUserInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertAccountInfo", ReplyAction="http://tempuri.org/IService1/InsertAccountInfoResponse")]
        string InsertAccountInfo(ObjectData.AccountInfo acInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertAccountInfo", ReplyAction="http://tempuri.org/IService1/InsertAccountInfoResponse")]
        System.Threading.Tasks.Task<string> InsertAccountInfoAsync(ObjectData.AccountInfo acInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateAccountInfo", ReplyAction="http://tempuri.org/IService1/UpdateAccountInfoResponse")]
        string UpdateAccountInfo(ObjectData.AccountInfo acInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateAccountInfo", ReplyAction="http://tempuri.org/IService1/UpdateAccountInfoResponse")]
        System.Threading.Tasks.Task<string> UpdateAccountInfoAsync(ObjectData.AccountInfo acInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAccountInfo", ReplyAction="http://tempuri.org/IService1/SelectAccountInfoResponse")]
        System.Data.DataSet SelectAccountInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAccountInfo", ReplyAction="http://tempuri.org/IService1/SelectAccountInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectAccountInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAccountInfo", ReplyAction="http://tempuri.org/IService1/DeleteAccountInfoResponse")]
        string DeleteAccountInfo(int idInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAccountInfo", ReplyAction="http://tempuri.org/IService1/DeleteAccountInfoResponse")]
        System.Threading.Tasks.Task<string> DeleteAccountInfoAsync(int idInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AccountManagement.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AccountManagement.ServiceReference1.IService1>, AccountManagement.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetUserInfo() {
            return base.Channel.GetUserInfo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUserInfoAsync() {
            return base.Channel.GetUserInfoAsync();
        }
        
        public string InsertAccountInfo(ObjectData.AccountInfo acInfo) {
            return base.Channel.InsertAccountInfo(acInfo);
        }
        
        public System.Threading.Tasks.Task<string> InsertAccountInfoAsync(ObjectData.AccountInfo acInfo) {
            return base.Channel.InsertAccountInfoAsync(acInfo);
        }
        
        public string UpdateAccountInfo(ObjectData.AccountInfo acInfo) {
            return base.Channel.UpdateAccountInfo(acInfo);
        }
        
        public System.Threading.Tasks.Task<string> UpdateAccountInfoAsync(ObjectData.AccountInfo acInfo) {
            return base.Channel.UpdateAccountInfoAsync(acInfo);
        }
        
        public System.Data.DataSet SelectAccountInfo() {
            return base.Channel.SelectAccountInfo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectAccountInfoAsync() {
            return base.Channel.SelectAccountInfoAsync();
        }
        
        public string DeleteAccountInfo(int idInfo) {
            return base.Channel.DeleteAccountInfo(idInfo);
        }
        
        public System.Threading.Tasks.Task<string> DeleteAccountInfoAsync(int idInfo) {
            return base.Channel.DeleteAccountInfoAsync(idInfo);
        }
    }
}
